### PR TITLE
#3: fix line endings with gitattributes

### PR DESCRIPTION
**Pull request by tobka777**
#3 

This is one solution I came across to configure the LineEndings. I would be interested to know if this solves the problem. 

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

### CODE REVIEW

**Comment by tobka777** [comment]
Could you guys test how these changes work for you? @cinnamon-coder-hub @CREITZ25

**Comment by cinnamon-coder-hub** [comment]
@tobka777  I checked the option 'git config --global core.autocrlf' on Windows 10 with true and false while inserting CRLF for the line ending via VSCode and checking if CRLF was really inserted with Notepad ++. In both cases CRLF was converted to LF when downloading the code from github via raw code and right click to save the page in my case as a txt-file.

**Comment by tobka777** [comment]
Please check with my `.gitattributes`: https://github.com/tobka777/ide-mirrors/blob/fix/3-line-endings/.gitattributes

**Review by hohwille — APPROVED** [review]
@tobka777 thanks for the PR and this solution.

**Pull request merged**
