### PR TITLE
#22 Fix java mirrors for macos

### PR DESCRIPTION
**Pull request by alfeilex**
#22

### CODE REVIEW

**Comment by hohwille** [comment]
@alfeilex thanks for this PR. Great finding and solution👍 
It seems that for some tools or versions new M1 architecture releases are not available.
You changed this globally to x86.
I was not aware that this already helps due to Rosetta emulation that seems to perfectly cope with the situation.

However, newer versions of Java do actually provide real M1 support what gives you a significant performance boost compared to emulation. Could you please test this (edit `JAVA_VERSION` in devon.properties and set to latest Java 17 and try `devon java setup` on Mac with M1)

Therefore we should IMHO not change this globally.
For Java I would suggest the following:
* rename `Adoptium` folder to `Temurin` (nothing directly related with this issue, but to resolve confusion).
* move your actual change to the two subfolders of Java so only for older releases that have no M1 support we fall back to x86.
* See also devonfw/ide#805

For node.js your workaround seems to be the only solution so far as there is no M1 support available:
https://nodejs.org/en/download/

p.s.: When providing smaller PRs for each tool it is sometimes easier and faster to get PRs merged (so e.g. node.js could already be merged as is).

**Comment by alfeilex** [comment]
Java Version 17.0.3_7 works for the remote M1 Mac

**Review by hohwille — APPROVED** [review]
@alfeilex Excellent. Thanks for the correction. Now looks perfect to me. 👍

**Comment by hohwille** [comment]
Fix for https://github.com/devonfw/ide/issues/805

**Comment by alfeilex** [comment]
@alfeilex @hohwille 
Does it have a reason why we map `arm64=aarch64` here instead of `arm64=x64`?
https://github.com/devonfw/ide-mirrors/blob/edbb9e4cfc133223cea4c0a09a2cc3334b18cae4/java/arch-mappings#L2

Maybe I missed that in this PR. It causes problems while installing Java 11 on m1 machines.

**Pull request merged**
